services:
  spiderfoot-ng:
    container_name: spiderfoot-ng
    image: ghcr.io/sammothxc/spiderfoot-ng
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - spiderfoot-ng:/var/lib/spiderfoot

volumes:
  spiderfoot-ng:
